apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tarsy
  namespace: tarsy
spec: {}

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tarsy-llm
  namespace: tarsy
spec: {}
